### ISSUE TITLE
README instructions have various issues

### ISSUE THREAD

**Issue by sezna** [calebwin/emu#33]
As mentioned in #31 , I'm migrating my project to use the new `emu_core` GLSL abstraction layer and I am encountering a few documentation issues getting started.

In the dependencies section, it is said that this is how you add `emu` to a project:
```
emu_core = {
    git = "https://github.com/calebwin/emu/tree/master/emu_core.git",
    rev = "265d2a5fb9292e2644ae4431f2982523a8d27a0f"
}
```
Newlines inside of a dep key in Cargo are invalid, and also this isn't a valid Git URL. Currently, the only way I see to use `emu_core` is to clone the whole `emu` repository and then use a path dependency. In workspace setups, typically the individual crates are published to crates.io individually, avoiding this issue. 

Additionally, there's a discord link at the bottom of the README that I was going to use to address the above question, but the Discord invite is invalid. 

The only person who can fix these issues would be @calebwin so that's why I'm filing an issue instead of a PR. Thanks again for the crate -- I'll be using it with the cloned dependency for now.

**Comment by calebwin** [comment]
There are 2 ways I see to resolve this.

1. Publish to Crates.io. We can't do this yet because we depend on the latest version of wgpu-rs pulled straight from GitHub. When they publish wgpu-rs to Crates.io, I plan on publishing then.

2. Somehow use git. I honestly don't know how to do this without making `emu_core` a separate GitHub repository.

I think for now cloning is probably the only way to do this, I guess. Are you publishing to Crates.io now? If you're doing it some time in the next few months, I'm sure wgpu-rs will get published by then and emu_core can then be published as well.

Sorry for the inconvenience, though.

**Comment by sezna** [comment]
Not too big of a problem for me but I figured it would be worth tracking.

I'm not publishing this version very soon. I think a good temporary resolution would be to update the README so that the dependency section and discord section are accurate and then perhaps keeping this issue open to track crates.io publishing?

**Comment by calebwin** [comment]
Yeah. `wgpu-rs` should be published some time [soon](https://github.com/gfx-rs/wgpu-rs/milestone/1) and when it is, I'll publish Emu. Incidentally, I'm also trying to use Emu in a different project and for now, I'm just cloning it into the separate project.

**Comment by calebwin** [comment]
@sezna I don't know if you already know but I recently released `emu_core` on [Crates.io](https://crates.io/crates/emu_core) with docs [here](https://calebwin.github.io/emu/).
